name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodule
      run: |
        git submodule update --init

    - name: Install cross-toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain-arm64.cmake ..
        cmake --build .

    - name: Package
      run: |
        mkdir package
        cp ${{ github.workspace }}/lib/openssl/libssl.so package/
        cp ${{ github.workspace }}/lib/openssl/libcrypto.so package/
        cp build/dns-gateway package/

        version=$(git describe --tags --always)
        package_filename="dns-gateway_${version}.zip"
        zip -r $package_filename package

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: "dns-gateway_${version}.zip"
          path: |
            ./gateway_-${version}/*